name: mmama

on:

  
  workflow_dispatch:
jobs:
     build-using-maven:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6.0.1
            - name: building using maven
              run: pwd
